name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint Code
    runs-on: macos-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Lint
        run: swiftlint
  test:
    name: Test  ${{ matrix.platform }} using Xcode ${{ matrix.xcode }}
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - ^12
          - ^13
        scheme: ["TelemetryClient"]
        command: ["test"]
        platform: ["macOS", "iOS"]
        sdk: ["iphonesimulator14.5", "iphonesimulator15.2"]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Build and Test
        run: xcodebuild test -scheme TelemetryClient -sdk ${{ matrix.sdk }} -destination "name=iPhone 13 Mini"
