name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint Code
    runs-on: macos-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Lint
        run: swiftlint
  test:
    name: Test Xcode ${{ matrix.xcode }} - ${{ matrix.xcodebuildCommand }}
    runs-on: "macos-latest"
    strategy:
      fail-fast: true
      matrix:
        xcode:
          - ^12
          - ^13
        xcodebuildCommand:
          - "-sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'"
          - "-sdk macosx -destination 'platform=macOS'"
          - "-sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 4K (2nd generation)'"
          - "-sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm'"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Build and Test
        run: xcodebuild test -scheme TelemetryClient ${{ matrix.xcodebuildCommand }}
