name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint Code
    runs-on: macos-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Lint
        run: swiftlint
  test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - ^12
          - ^13
        macos: ["macos-11"]
        scheme: ["TelemetryClient"]
        command: ["test"]
        platform: ["macOS", "iOS", "tvOS", "watchOS", "mac-catalyst"]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Build and Test
        uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          scheme: ${{ matrix.scheme }}
          action: ${{ matrix.command }}
          code-coverage: false
          verbosity: xcpretty
          upload-logs: always
