name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Lint
        run: swiftlint
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
        swift: ["5.3", "5.4", "5.5", "5.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
